### ISSUE TITLE
Set up a public #digitaltwins channel on the Turing Slack

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/tric-dt#1]
David Wagg has approved the creation of a public "digital-twins" channel to be hosted on Turing slack. The channel is explicitly named to include all Turing DT work (i.e. across all Grand Challenges) and not only those directly supported by TRIC.

## Actions
- [x] Confirm with @kallewesterling requirements for public slack channel
- [x] #15
- [x] Transfer ownership to Hub
    - [x] @aranas to contact Achintya Rao - current owner of this slack, now moved on from Turing?
- [x] Collect and add contributors
    - [x] Invite Co-Directors (Scott, David, Keith, Steve, Kirstine)
    - [x] Invite PDRAs (Jack Poole, Mohamad Elmasri, Ziad Ghauch, Xiaoxue, Chris Lindley)
    - [x] Invite PMU (Janine and Karen)
- [X] Set channel description
- [x] Add a "welcome" guide: https://alan-turing-institute.slack.com/archives/C03F3DVDQKE/p1697198729439319
- [ ] Advertise

**Comment by kallewesterling** [comment]
> Transfer ownership to Hub

@aranas and I discussed this, and we don't think there's a need to transfer the ownership. We have all the necessary permissions to edit anything.

**Comment by kallewesterling** [comment]
Edited the bullet point list above to add some names - in order to be as concrete as possible.

**Comment by kallewesterling** [comment]
Not sure what's needed in terms of "advertising" except just keeping the channel busy with messages 💌 

Otherwise, I've added/invited/made sure that all the co-directors, PDRAs, and PMU are in the channel.

**Comment by aranas** [comment]
yep, I think we're good on this one. @cassgvp ?

**Comment by chrisdburr** [comment]
This has now been completed. A separate issue can be created for plans around advertising, invites, and ongoing maintenance.
