### ISSUE TITLE
[Topic] Emulators for Scaling-up Simulations

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/tric-dt#12]
**Topic**
Scaling-up simulations: Exploration of the role of emulators in bridging the gap between high-fidelity models and real-time requirements of digital twins.

**How is the topic relevant to the tric-dt themes?**
Emulators are a general method relevant for many DT solutions. Both Health and Environment themes already work with emulators in some capacity

**How does it relate to the wider topic of digital twinning?**
Emulators may be crucial to create fast and efficient approximations of complex DT models, allowing for real-time simulations & predictions. 

**Suggested speakers or contributors**
@MarinaStrocchi or Cristóbal Rodero (Health theme) to speak to demands on emulators for clinical practice
Martin Stoffel to present Autoemulate project

**Any resources you can recommend on this topic?**

**What format do you think would serve this topic best?**
seminar series

**Comment by aranas** [comment]
@ludovica-cicci mentioned in our conversation that physics-based reduced order models is something that could be relevant here. What do people think?

**Comment by aranas** [comment]
@mastoffel, as briefly mentioned on slack, I think it would be great if you could share your work on [autoemulate](https://github.com/alan-turing-institute/autoemulate) with the wider group, if you'd be up for it, maybe you could share a proposed title and some description for what you'd talk about.

**Comment by aranas** [comment]
In terms of scaling up, another interesting conversation to be had might be **automatising DTs using reinforcement learning approaches**. @ZGGhauch, you brought this up as a topic you will focus on in your work. Do you think it would be best to have a separate session for this or is there a way to connect this to the emulators work going on? If a different seesion, maybe you'd like to open a new issue with some suggestions discussion points so others can feed into it. Also a question for researchers from the Health & Environment themes, is RL something that matters for your work?

**Comment by aranas** [comment]
@nickmalleson tagging you here as you expressed interest in connecting and I saw you had some papers out on related work (eg [this one](https://www.tandfonline.com/doi/abs/10.1080/17477778.2022.2080008)) 
Feel free to pitch in re topics you think might be of interest for the seminar series. See our seminars page [for how to contribute](https://github.com/alan-turing-institute/tric-dt/tree/main/Seminars)

**Comment by mastoffel** [comment]
@aranas: Abstract for my talk on the 23rd in the TRIC-DT seminar series:

Simulations can be slow and compute-intensive, which is why we often train emulator models to replace them for real world applications and research.  However, choosing and training a good emulator model is difficult, because there are lots of potential models, each with many parameters. To make emulation easier, we are developing [autoemulate](https://github.com/alan-turing-institute/autoemulate) a Python package that automatically evaluates a variety of emulator models and returns the one that fits best. In this talk, I'll give an overview over the package so far and an outline for the near future.

**Comment by aranas** [comment]
and abstract for @MarinaStrocchi presentation:
Computational models of the heart and cardiac digital twins offer a non-invasive tool to link the molecular processes to whole-heart function in a physics-constrained framework. However, the cost of the simulations hinders their application in a clinical setting. Artificial intelligence (AI) can be used to reduce the cost of model evaluations and accelerate clinical translation of computational models. Gaussian processes emulators (GPEs) constitute an example of AI tools that suit this purpose. In this presentation, we will look into the GPEs we use in our research, together with some examples to showcase their use.

**Comment by aranas** [comment]
Thanks again everyone for a great first seminar! 
Here is our notes doc:
https://hackmd.io/ym-FDwrZQpuZkMDMQkMDXQ

**Comment by kallewesterling** [comment]
Congratulations again to @aranas @MarinaStrocchi @mastoffel to a great first seminar!!! 🎉
