### ISSUE TITLE
Create Code of Conduct for TRIC-DT community

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/tric-dt#16]

**Comment by kallewesterling** [comment]
@cassgvp do you have good examples that we can reuse (with CC license or so)?

**Comment by cassgvp** [comment]
I suggest we not create one ourselves as that will require maintenance and governance planning. 

For events we should use the [Turing Events COC](https://www.turing.ac.uk/events/policies-and-guidelines)

As we develop the community, I would look to see if/where/when it is appropriate to move towards the [TTW COC](https://the-turing-way.netlify.app/community-handbook/coc)

**Comment by cassgvp** [comment]
Please close if you agree @chrisdburr @aranas @kallewesterling :)

**Comment by aranas** [comment]
Yes great suggestion, let's do that!
