### ISSUE TITLE
Add internal contributors to this repo

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/tric-dt#2]
This is a public-facing repo and should include all (internal) members of TRIC-DT as collaborators. List below to collect github usernames and add to permissions.

- [X] David Wagg @davidjwagg 
- [X] Scott Hosking @scotthosking
- [x] Kirstine Dale _Does not have a GitHub username_
- [X] Keith Worden @me1kw
- [X] Steve Niederer @snie007
- [x] Ziad Ghauch @ZGGhauch
- [x] Janine @janinecoomber
- [x] Other PDRAs
    - [X] @MarinaStrocchi
    - [X] @ShenXiaoxue

**Comment by kallewesterling** [comment]
@cassgvp do you mean that we should add them as "contributors" in the README? Or you mean to the GitHub repository? Happy to help here. I can write to the co-directors asking them for their GitHub usernames if you haven't done so already?

**Comment by cassgvp** [comment]
I meant just adding people in the repo settings :). We will separately create a CITATION.cff and add all-contributors :) (I'll update this comment with issue links)

Would be wonderful if you could get the co-directors usernames! Please could you add them with "write" access?

I will also record the short "intro to github" demo we are doing for Janine and Karen on Friday 20th October. Might be useful to share with the Co-Directors :)

**Comment by kallewesterling** [comment]
- [ ] Add @kdecesare as well :)

**Comment by kallewesterling** [comment]
Invited @janinecoomber to the repo.

**Comment by kallewesterling** [comment]
Invited @me1kw and @snie007 to the repo, and clarified the comment above somewhat.

**Comment by kallewesterling** [comment]
Emailed Kirstine Dale about her GitHub username.

**Comment by cassgvp** [comment]
I think we've done pretty well collecting folks here! Closing this issue now :)

**Comment by kallewesterling** [comment]
I followed up with Kirstine to see if we can have her username as well before we can close this out completely.

**Comment by kallewesterling** [comment]
Just assigning it to myself, so should be off your radar @cassgvp !

**Comment by kallewesterling** [comment]
I followed up with Kirstine one last time.
