### ISSUE TITLE
Add to ways of working official dt email

### ISSUE THREAD

**Issue by aranas** [alan-turing-institute/tric-dt#27]
For the Seminar Series, David has asked for communication to be send via digitaltwins@turing.ac.uk. 
Once I got it working, I will add a section about it to our WoW:

- [x] How we use the digitaltwins turing email (when and how should you request access to it)
- [x] How to add another mailbox to. your outlook

**Comment by chrisdburr** [comment]
As @cassgvp has noted, we need to ensure that this email is used throughout our project pages.

**Comment by aranas** [comment]
there is a actually a bit of a blocker, I can still not send emails from that mailbox, only view the incoming mail. I need to follow-up with IT about it.

**Comment by aranas** [comment]
this issue with the mailbox was easily resolved by IT so no need to update the WoW based on this blocker. @chrisdburr from my side this issue can be closed.
