### ISSUE TITLE
Add CONTRIBUTING and Issue templates

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/tric-dt#4]
Add information to the repository about community guidelines and best practices.

- [ ] Add `CONTRIBUTING.md`
- [x] Add community information to the repository's README
- [x] Add issue templates to `.github/[ISSUE_TEMPLATE]`

**Comment by cassgvp** [comment]
This should be split off into two issues 1) contributing, 2) issue templates

**Comment by cassgvp** [comment]
I've added the issue template from the RCM team, which I quite like.

**Comment by kallewesterling** [comment]
Moving over `- [ ] Add CONTRIBUTING.md` into a separate issue, as you mentioned above @cassgvp!
